[build]
  command = "npm run build && mkdir -p dist/src && cp -r src/content dist/src/content"
  publish = "dist"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "*.md"
  [headers.values]
    Content-Type = "text/markdown; charset=utf-8"
    
[[headers]]
  for = "*.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"